### PR TITLE
do the funni routing thing

### PR DESCRIPTION
**Pull request by tizu69**
static site hosting ain't got this :3

### CODE REVIEW

**Comment by tizu69** [comment]
shut up netlify bot

**Comment by tizu69** [comment]
shut the fuck up

**Comment by tizu69** [comment]
i aint doing all dat

**Comment by tizu69** [comment]
hey gcast wen review (I aint fixing this, the 20 lines I changed shouldn't break shit ykyk)

**Comment by Gcat101** [comment]
was this tested

**Comment by tizu69** [comment]
> was this tested

mostly

**Comment by Gcat101** [comment]
k I'm just gonna trust you

**Pull request merged**
