### PR TITLE
feat/new UI

### PR DESCRIPTION
**Pull request by tizu69**
uwu owo new ui :3
> https://tizu69.github.io/kjspkg-lookup/

notes:
1. change the base path in svelte.config.js if needed
2. change automatin' target url in /src/lib/consts once ready
3. zeldalord activate windows

### CODE REVIEW

**Comment by tizu69** [comment]
image

> It is not required to merge. 

image

**Comment by Gcat101** [comment]
Ig

**Comment by Gcat101** [comment]
Jk, based pr, lgtm

**Comment by tizu69** [comment]
YOU DIDN'T EVEN REVIEW THE THINGY :ahujel:

**Pull request merged**
